apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notes-api
  name: notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notes-api
    spec:
      containers:
      - image: yusuffranklin/notes-api:latest
        name: notes-api
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
          limits:
            cpu: "70m"
            memory: "20Mi"
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_URL
status: {}
