apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notes-api
  name: notes-api-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: notes-api
  type: LoadBalancer
status:
  loadBalancer: {}
