apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-services
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: notes-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
