apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if eq .Values.autoscaling.enabled false }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        name: {{ .Release.Name }}
        {{- with .Values.deployment.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        {{- range .Values.deployment.env }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}

