apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
  {{- range .Values.service.ports }}
    - port: {{ .name }}
      interval: 15s
  {{- end}}